---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: base-repository-team1
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/akahenry/k8s-base-team1
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k8s-prd-team1
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: ssh://git@github.com/akahenry/k8s-prd-team1
  include:
    - repository:
        name: base-repository-team1
      toPath: base-repository
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: k8s-prd-team1
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kind
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-prd-team1
  validation: client
